# Default initial positions for ur5's ros2_control fake system

initial_positions:
  elbow_joint: 0.0
  gripper_joint1: 0.0
  shoulder_lift_joint: 0.0
  shoulder_pan_joint: 0.0
  wrist_1_joint: 0.0
  wrist_2_joint: 0.0
  wrist_3_joint: 0.0